@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@baseUrl = {{protocol}}://{{domainname}}:{{port}}

### Route GET /cocktails

GET {{baseUrl}}/cocktails

### Route GET /cocktails/:id

GET {{baseUrl}}/cocktails/8

### Route POST /cocktails

POST {{baseUrl}}/cocktails
Content-type: application/json

{
    "name": "Tequila Sunrise",
    "ingredients": "Tequila, Jus d'orange, Sirop de grenadine, Glaçons",
    "instructions": "Dans un verre long drink rempli de glaçons, versez dans l’ordre 4 cl de tequila et 8 cl de jus d’orange.\nRemuez doucement. Versez lentement 2 cl de sirop de grenadine en vérifiant que le sirop tombe bien au fond du verre.\nDonnez un petit coup de cuillère à cocktail pour créer un joli dégradé typique de la Tequila Sunrise.",
    "glass": "Verre à cocktail",
    "picturesLink": "https://www.destinationcocktails.fr/wp-content/uploads/2019/11/cocktail-tequila-sunrise.jpg"
}

### Route DELETE /cocktails
DELETE {{baseUrl}}/cocktails/6

### Route POST /cocktails

PATCH {{baseUrl}}/cocktails/8
Content-type: application/json

{
    "glass": "Verre à cocktail ou tout type de grand verre"
}